### ISSUE TITLE
Tracking error

### ISSUE THREAD

**Issue by MSathishkumar1990** [XU-TIANYANG/GFS-DCF#2]
I am getting this issue while running the code

Undefined variable "dagnn" or class "dagnn.DagNN.loadobj".

Error in init_features (line 111)
        net = dagnn.DagNN.loadobj(features{k}.fparams.nn_name);

Error in tracker_main (line 103)
[features, global_fparams, feature_info] = init_features(features, global_fparams, params, is_color_image, img_sample_sz, 'odd_cells');

Error in run_GFSDCF (line 76)
[results] = tracker_main(params);

Error in demo (line 18)
results = run_GFSDCF(seq);
 
111         net = dagnn.DagNN.loadobj(features{k}.fparams.nn_name);

**Comment by XU-TIANYANG** [comment]
You need a compiled matconvnet toolbox (http://www.vlfeat.org/matconvnet/).
